USE [master]
GO
/****** Object:  Database [ExOptativoIII]    Script Date: 6/19/2024 7:36:33 AM ******/
CREATE DATABASE [ExOptativoIII]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ExOptativoIII', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ExOptativoIII.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ExOptativoIII_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ExOptativoIII_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ExOptativoIII] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ExOptativoIII].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ExOptativoIII] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ExOptativoIII] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ExOptativoIII] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ExOptativoIII] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ExOptativoIII] SET ARITHABORT OFF 
GO
ALTER DATABASE [ExOptativoIII] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ExOptativoIII] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ExOptativoIII] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ExOptativoIII] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ExOptativoIII] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ExOptativoIII] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ExOptativoIII] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ExOptativoIII] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ExOptativoIII] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ExOptativoIII] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ExOptativoIII] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ExOptativoIII] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ExOptativoIII] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ExOptativoIII] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ExOptativoIII] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ExOptativoIII] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ExOptativoIII] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ExOptativoIII] SET RECOVERY FULL 
GO
ALTER DATABASE [ExOptativoIII] SET  MULTI_USER 
GO
ALTER DATABASE [ExOptativoIII] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ExOptativoIII] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ExOptativoIII] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ExOptativoIII] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ExOptativoIII] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ExOptativoIII] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ExOptativoIII', N'ON'
GO
ALTER DATABASE [ExOptativoIII] SET QUERY_STORE = ON
GO
ALTER DATABASE [ExOptativoIII] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ExOptativoIII]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 6/19/2024 7:36:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Id_Banco] [int] NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Apellido] [nvarchar](100) NOT NULL,
	[Documento] [nvarchar](10) NOT NULL,
	[Direccion] [nvarchar](255) NOT NULL,
	[Mail] [nvarchar](100) NOT NULL,
	[Celular] [nvarchar](10) NOT NULL,
	[Estado] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DetalleFactura]    Script Date: 6/19/2024 7:36:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DetalleFactura](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Id_Factura] [int] NULL,
	[Id_Producto] [int] NULL,
	[Cantidad_Producto] [int] NOT NULL,
	[Subtotal] [decimal](18, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Factura]    Script Date: 6/19/2024 7:36:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Factura](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Id_Cliente] [int] NULL,
	[Id_Sucursal] [int] NULL,
	[Nro_Factura] [nvarchar](20) NOT NULL,
	[Fecha_Hora] [nvarchar](20) NOT NULL,
	[Total] [decimal](18, 2) NOT NULL,
	[Total_iva5] [decimal](18, 2) NOT NULL,
	[Total_iva10] [decimal](18, 2) NOT NULL,
	[Total_iva] [decimal](18, 2) NOT NULL,
	[Total_Letras] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Productos]    Script Date: 6/19/2024 7:36:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Productos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](100) NOT NULL,
	[Cantidad_Minima] [int] NOT NULL,
	[Cantidad_Stock] [int] NOT NULL,
	[Precio_Compra] [int] NOT NULL,
	[Precio_Venta] [int] NOT NULL,
	[Categoria] [nvarchar](100) NOT NULL,
	[Marca] [nvarchar](100) NOT NULL,
	[Estado] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sucursal]    Script Date: 6/19/2024 7:36:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sucursal](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](100) NOT NULL,
	[Direccion] [nvarchar](255) NOT NULL,
	[Telefono] [nvarchar](100) NOT NULL,
	[Whatsapp] [nvarchar](100) NOT NULL,
	[Mail] [nvarchar](100) NOT NULL,
	[Estado] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DetalleFactura]  WITH CHECK ADD FOREIGN KEY([Id_Factura])
REFERENCES [dbo].[Factura] ([Id])
GO
ALTER TABLE [dbo].[DetalleFactura]  WITH CHECK ADD FOREIGN KEY([Id_Producto])
REFERENCES [dbo].[Productos] ([Id])
GO
ALTER TABLE [dbo].[Factura]  WITH CHECK ADD FOREIGN KEY([Id_Cliente])
REFERENCES [dbo].[Cliente] ([Id])
GO
ALTER TABLE [dbo].[Factura]  WITH CHECK ADD FOREIGN KEY([Id_Sucursal])
REFERENCES [dbo].[Sucursal] ([Id])
GO
USE [master]
GO
ALTER DATABASE [ExOptativoIII] SET  READ_WRITE 
GO
